/* ───────────────────────────────────────────────────────────────────────────
   MERA BISTROT — i dati del menù.

   Questo è l'unico file da toccare per cambiare piatti, prezzi o traduzioni.
   La pagina (menu.html) non va mai modificata per un cambio di listino.

   Ogni voce:  { it:'nome italiano', en:'english name',
                 dit:'descrizione',  den:'description',   // facoltative
                 p:'11' }                                  // prezzo, senza €

   Contenuto trascritto dal menù in uso (digitalmenucheck.com, 11 pagine).
   ─────────────────────────────────────────────────────────────────────────── */

const LOCALE = {
  nome: 'Mera Bistrot',
  via: 'Via Merulana 106/107 · Roma',
  taglio: 'Via Merulana 108',
  tel: '+390686299500', telLabel: '06 86299500',
  wa: '39375910047', waLabel: '375 910047',
  orari: { it: 'Tutti i giorni 7:30 — 22:00', en: 'Every day 7:30 — 22:00' },
  wifi: { rete: 'Mera Bistrot', pass: 'DA DEFINIRE' },
  recensioni: {
    google: 'https://www.google.com/maps/search/?api=1&query=MERA%20Bistrot%20%26%20Cafe%27&query_place_id=ChIJcVcAfiRhLxMROKVtWWs08YQ',
    tripadvisor: 'https://www.tripadvisor.it/'
  },
  mappa: 'https://maps.google.com/?q=Via+Merulana+106,+Roma'
};

const SEZIONI = [

/* ══ I ═══ COLAZIONE ══════════════════════════════════════════════════════ */
{ id: 'colazione', it: 'Colazione', en: 'Breakfast',
  ore: '8:40 — 16:00', foto: '../img/w_foto_colazione.jpg',
  nota: { it: 'Servita fino alle 16:00, anche nel pomeriggio.',
          en: 'Served until 16:00, afternoons included.' },
  gruppi: [
  { it: 'Dolci', en: 'Sweet', voci: [
    { it: 'Macedonia di frutta', en: 'Fruit salad', p: '5' },
    { it: 'Waffle', en: 'Waffle', p: '8',
      dit: 'Nutella o sciroppo d’acero, frutta fresca',
      den: 'Nutella or maple syrup, fresh fruit' },
    { it: 'Porridge', en: 'Porridge', p: '9',
      dit: 'Fiocchi d’avena cotti in acqua o latte, con frutta fresca',
      den: 'Oats cooked in water or milk, with fresh fruit' },
    { it: 'Pancake', en: 'Pancakes', p: '9',
      dit: 'Nutella o sciroppo d’acero, frutta fresca',
      den: 'Nutella or maple syrup, fresh fruit' },
    { it: 'Bowl di yogurt', en: 'Yogurt bowl', p: '9',
      dit: 'Yogurt cremoso con granola e frutta fresca',
      den: 'Creamy yogurt with granola and fresh fruit' } ] },

  { it: 'Salate', en: 'Savoury', voci: [
    { it: 'Toast cotto', en: 'Ham toastie', p: '8',
      dit: 'Prosciutto cotto, insalata e bufala',
      den: 'Cooked ham, lettuce and buffalo mozzarella' },
    { it: 'Toast crudo', en: 'Prosciutto toastie', p: '8',
      dit: 'Prosciutto crudo, insalata e stracciatella',
      den: 'Cured ham, lettuce and stracciatella' },
    { it: 'Toast al salmone', en: 'Salmon toastie', p: '10',
      dit: 'Salmone affumicato, crema al formaggio e avocado',
      den: 'Smoked salmon, cream cheese and avocado' },
    { it: 'Uova strapazzate con bacon', en: 'Scrambled eggs with bacon', p: '11',
      dit: 'Pane bruscato e insalata', den: 'Toasted bread and salad' },
    { it: 'Uova strapazzate con würstel', en: 'Scrambled eggs with frankfurters', p: '11',
      dit: 'Pane bruscato e insalata', den: 'Toasted bread and salad' },
    { it: 'Omelette vegetariana', en: 'Vegetarian omelette', p: '12',
      dit: 'Uova, zucchine, parmigiano', den: 'Eggs, courgettes, parmesan' },
    { it: 'Omelette classica', en: 'Classic omelette', p: '12',
      dit: 'Uova, prosciutto cotto, cheddar e bacon',
      den: 'Eggs, cooked ham, cheddar and bacon' },
    { it: 'Maxi club sandwich classic', en: 'Maxi club sandwich', p: '15',
      dit: 'Pane tostato, prosciutto cotto, uova, bacon croccante, lattuga, pomodoro, maionese, cheddar',
      den: 'Toasted bread, cooked ham, egg, crispy bacon, lettuce, tomato, mayo, cheddar' } ] },

  { it: 'Formule colazione', en: 'Breakfast sets', evidenza: true, voci: [
    { it: 'All’Italiana', en: 'The Italian one', p: '9',
      dit: 'Torta del giorno o crostata + spremuta d’arancia + caffè o cappuccino',
      den: 'Cake of the day or tart + orange juice + coffee or cappuccino' },
    { it: 'Dolce', en: 'Sweet', p: '13',
      dit: 'Dolce a scelta + spremuta d’arancia + caffè o cappuccino',
      den: 'Any sweet dish + orange juice + coffee or cappuccino' },
    { it: 'Salata', en: 'Savoury', p: '16',
      dit: 'Colazione salata a scelta (escluso maxi club sandwich) + spremuta + caffè o cappuccino',
      den: 'Any savoury dish (maxi club sandwich excluded) + juice + coffee or cappuccino' },
    { it: 'Maxi club sandwich', en: 'Maxi club sandwich set', p: '19',
      dit: 'Spremuta d’arancia + caffè o cappuccino',
      den: 'Orange juice + coffee or cappuccino' },
    { it: 'Macedonia', en: 'Fruit salad set', p: '10',
      dit: 'Spremuta d’arancia + caffè o cappuccino',
      den: 'Orange juice + coffee or cappuccino' } ] } ] },

/* ══ II ══ CAFFETTERIA ════════════════════════════════════════════════════ */
{ id: 'caffetteria', it: 'Caffetteria', en: 'Coffee bar',
  ore: { it: 'TUTTO IL GIORNO', en: 'ALL DAY' },
  gruppi: [
  { it: 'Al banco', en: 'At the counter', fitto: true, voci: [
    { it: 'Caffè', en: 'Espresso', p: '1,70' },
    { it: 'Caffè decaffeinato', en: 'Decaf espresso', p: '1,80' },
    { it: 'Caffè latte', en: 'Latte', p: '2,20' },
    { it: 'Caffè freddo', en: 'Iced coffee', p: '2,20' },
    { it: 'Caffè corretto', en: 'Espresso with a shot', p: '2,80' },
    { it: 'Caffè doppio', en: 'Double espresso', p: '3,00' },
    { it: 'Latte bianco', en: 'Warm milk', p: '1,90' },
    { it: 'Cappuccino', en: 'Cappuccino', p: '2,00' },
    { it: 'Cappuccino freddo', en: 'Iced cappuccino', p: '2,00' },
    { it: 'Cappuccino deca o senza lattosio', en: 'Decaf or lactose-free cappuccino', p: '2,20' },
    { it: 'Cappuccino orzo o ginseng', en: 'Barley or ginseng cappuccino', p: '2,40' },
    { it: 'Cappuccino grande', en: 'Large cappuccino', p: '3,40' },
    { it: 'Orzo piccolo', en: 'Barley coffee, small', p: '1,90' },
    { it: 'Orzo grande', en: 'Barley coffee, large', p: '2,40' },
    { it: 'Ginseng piccolo', en: 'Ginseng coffee, small', p: '1,90' },
    { it: 'Ginseng grande', en: 'Ginseng coffee, large', p: '2,40' },
    { it: 'Marocchino', en: 'Marocchino', p: '2,10' },
    { it: 'Americano', en: 'Americano', p: '2,40' },
    { it: 'Americano grande', en: 'Large americano', p: '3,40' },
    { it: 'Tè caldo', en: 'Hot tea', p: '2,50' },
    { it: 'Crema di caffè', en: 'Coffee cream', p: '4,00' },
    { it: 'Cioccolata calda', en: 'Hot chocolate', p: '4,00' } ] },

  { it: 'Cornetti e dolci da forno', en: 'Pastries', fitto: true, voci: [
    { it: 'Cornetti mignon', en: 'Mini croissants', p: '1,10' },
    { it: 'Cornetto classico', en: 'Plain croissant', p: '1,80' },
    { it: 'Cornetti farciti', en: 'Filled croissants', p: '2,00',
      dit: 'Crema, albicocca, visciole, cioccolato',
      den: 'Custard, apricot, sour cherry, chocolate' },
    { it: 'Ciambelle e bombe classiche', en: 'Plain doughnuts', p: '2,20' },
    { it: 'Ciambelle e bombe farcite', en: 'Filled doughnuts', p: '4,00',
      dit: 'Pistacchio, albicocca, visciole, cioccolato e frutta',
      den: 'Pistachio, apricot, sour cherry, chocolate and fruit' },
    { it: 'Ciambellone', en: 'Ring cake', p: '3,20' },
    { it: 'Crostata', en: 'Jam tart', p: '4,00' },
    { it: 'Torta del giorno', en: 'Cake of the day', p: '5,00' } ] },

  { it: 'Centrifughe', en: 'Juices', suffisso: '6', voci: [
    { it: 'Dissetante', en: 'Refreshing', dit: 'Mela, limone, zenzero',
      den: 'Apple, lemon, ginger' },
    { it: 'Drenante', en: 'Draining', dit: 'Pompelmo, cetriolo, finocchio',
      den: 'Grapefruit, cucumber, fennel' },
    { it: 'Depurativa', en: 'Cleansing', dit: 'Kiwi, sedano, melone, zenzero',
      den: 'Kiwi, celery, melon, ginger' },
    { it: 'Vitamina A-C', en: 'Vitamin A-C', dit: 'Carota, mango, arancia',
      den: 'Carrot, mango, orange' },
    { it: 'Detox', en: 'Detox', dit: 'Carota, sedano, finocchio',
      den: 'Carrot, celery, fennel' },
    { it: 'A scelta', en: 'Your own', dit: 'Con 3 frutti della lista',
      den: 'With 3 items from the list above' } ] } ] },

/* ══ III ═ ANTIPASTI ══════════════════════════════════════════════════════ */
{ id: 'antipasti', it: 'Antipasti', en: 'Starters',
  gruppi: [ { voci: [
    { it: 'Supplì al telefono', en: 'Classic supplì', p: '2,20' },
    { it: 'Crocchetta di patate', en: 'Potato croquette', p: '2,20' },
    { it: 'Supplì alla carbonara', en: 'Carbonara supplì', p: '3' },
    { it: 'Supplì all’amatriciana', en: 'Amatriciana supplì', p: '3' },
    { it: 'Bruschetta al pomodoro', en: 'Tomato bruschetta', p: '4',
      dit: '2 pezzi', den: '2 pieces' },
    { it: 'Bruschetta al pesto', en: 'Pesto bruschetta', p: '5',
      dit: 'Con pomodorini confit · 2 pezzi', den: 'With confit cherry tomatoes · 2 pieces' },
    { it: 'Bruschetta stracciatella e alici', en: 'Stracciatella and anchovy bruschetta', p: '6',
      dit: '2 pezzi', den: '2 pieces' },
    { it: 'Bruschetta salmone e stracciatella', en: 'Salmon and stracciatella bruschetta', p: '6',
      dit: '2 pezzi', den: '2 pieces' },
    { it: 'Tris di bruschette', en: 'Three bruschette', p: '8' },
    { it: 'Caprese', en: 'Caprese', p: '9' },
    { it: 'Crudo e bufala', en: 'Prosciutto and buffalo mozzarella', p: '13',
      dit: 'Accompagnati da una focaccia', den: 'Served with a focaccia' },
    { it: 'Tagliere di salumi', en: 'Cold cuts board', p: '22',
      dit: 'Con 2 focacce e mozzarella di bufala, per due persone',
      den: 'With 2 focacce and buffalo mozzarella, for two' } ] } ] },

/* ══ IV ══ PRIMI ══════════════════════════════════════════════════════════ */
{ id: 'primi', it: 'Primi piatti', en: 'Pasta',
  gruppi: [ { voci: [
    { it: 'Tonnarelli alla carbonara', en: 'Tonnarelli carbonara', p: '11' },
    { it: 'Tonnarelli all’amatriciana', en: 'Tonnarelli amatriciana', p: '11' },
    { it: 'Tonnarelli cacio e pepe', en: 'Tonnarelli cacio e pepe', p: '11' },
    { it: 'Tonnarelli alla gricia', en: 'Tonnarelli gricia', p: '11' },
    { it: 'Penne al pomodoro e basilico', en: 'Penne with tomato and basil', p: '10' },
    { it: 'Lasagna alla bolognese', en: 'Lasagne bolognese', p: '11' },
    { it: 'Fettuccine al ragù di manzo', en: 'Fettuccine with beef ragù', p: '11' },
    { it: 'Fettuccine Alfredo', en: 'Fettuccine Alfredo', p: '10' },
    { it: 'Fettuccine ai funghi porcini', en: 'Fettuccine with porcini', p: '12' },
    { it: 'Fettuccine al salmone', en: 'Fettuccine with salmon', p: '13' } ] } ] },

/* ══ V ═══ SECONDI ════════════════════════════════════════════════════════ */
{ id: 'secondi', it: 'Secondi e contorni', en: 'Mains and sides',
  gruppi: [
  { it: 'Secondi', en: 'Mains', voci: [
    { it: 'Polpette al sugo', en: 'Meatballs in tomato sauce', p: '8',
      dit: 'Morbide polpette di manzo nel sugo di pomodoro · 5 pezzi',
      den: 'Soft beef meatballs in tomato sauce · 5 pieces' },
    { it: 'Polpette all’amatriciana', en: 'Amatriciana meatballs', p: '10',
      dit: 'Polpette di manzo con guanciale in salsa all’amatriciana · 5 pezzi',
      den: 'Beef meatballs with guanciale in amatriciana sauce · 5 pieces' },
    { it: 'Polpette ai funghi porcini', en: 'Meatballs with porcini', p: '10',
      dit: 'Polpette di manzo in salsa ai funghi porcini · 5 pezzi',
      den: 'Beef meatballs in porcini sauce · 5 pieces' },
    { it: 'Polpette al ragù', en: 'Meatballs in ragù', p: '10',
      dit: 'Morbide polpette con salsa al ragù · 5 pezzi',
      den: 'Soft meatballs in ragù · 5 pieces' },
    { it: 'Hamburger al piatto', en: 'Beef patty, no bun', p: '11' },
    { it: 'Cotoletta di pollo', en: 'Breaded chicken cutlet', p: '9' },
    { it: 'Thai di pollo con verdure', en: 'Thai chicken with vegetables', p: '10' },
    { it: 'Tagliata di pollo', en: 'Sliced chicken', p: '13',
      dit: 'Pomodori confit, grana, salsa all’aceto balsamico',
      den: 'Confit tomatoes, grana, balsamic dressing' } ] },

  { it: 'Contorni', en: 'Sides', suffisso: '5', voci: [
    { it: 'Patate al forno', en: 'Roast potatoes' },
    { it: 'Patatine fritte', en: 'Chips' },
    { it: 'Cicoria alla romana', en: 'Roman chicory' },
    { it: 'Scarola', en: 'Escarole' },
    { it: 'Broccoli', en: 'Broccoli' } ] } ] },

/* ══ VI ══ INSALATONE E HAMBURGER ═════════════════════════════════════════ */
{ id: 'insalate', it: 'Insalatone e hamburger', en: 'Salads and burgers',
  gruppi: [
  { it: 'Insalatone', en: 'Big salads', voci: [
    { it: 'Mera', en: 'Mera', p: '11',
      dit: 'Lattuga, rughetta, pomodorini confit, tonno, olive nere, noci',
      den: 'Lettuce, rocket, confit tomatoes, tuna, black olives, walnuts' },
    { it: 'Classica', en: 'Classic', p: '9',
      dit: 'Lattuga, pomodorini, cetrioli, carote, cipolla rossa, olive nere',
      den: 'Lettuce, cherry tomatoes, cucumber, carrot, red onion, black olives' },
    { it: 'Caesar', en: 'Caesar', p: '12',
      dit: 'Lattuga, pollo grigliato, crostini, scaglie di grana, salsa Caesar',
      den: 'Lettuce, grilled chicken, croutons, grana shavings, Caesar dressing' },
    { it: 'Salmone', en: 'Salmon', p: '12',
      dit: 'Lattuga, salmone affumicato, avocado, cetrioli, pomodorini, semi di sesamo, salsa teriyaki',
      den: 'Lettuce, smoked salmon, avocado, cucumber, tomatoes, sesame, teriyaki' } ] },

  { it: 'Hamburger', en: 'Burgers', voci: [
    { it: 'Classico', en: 'Classic', p: '13',
      dit: 'Hamburger di manzo, lattuga, pomodoro, pane morbido + patatine fritte',
      den: 'Beef patty, lettuce, tomato, soft bun + chips' },
    { it: 'Cheeseburger', en: 'Cheeseburger', p: '14',
      dit: 'Hamburger di manzo, cheddar, lattuga, pomodoro, pane morbido + patatine fritte',
      den: 'Beef patty, cheddar, lettuce, tomato, soft bun + chips' },
    { it: 'Cheesebaconburger', en: 'Cheese and bacon burger', p: '15',
      dit: 'Hamburger di manzo, cheddar, bacon croccante, lattuga, pomodoro, pane morbido + patatine fritte',
      den: 'Beef patty, cheddar, crispy bacon, lettuce, tomato, soft bun + chips' } ] },

  { it: '', en: '', formula: true, voci: [
    { it: 'Formula hamburger', en: 'Burger set', p: '16',
      dit: 'Hamburger a scelta + contorno + bevanda',
      den: 'Any burger + a side + a drink' } ] } ] },

/* ══ VII ═ PIZZE ══════════════════════════════════════════════════════════ */
{ id: 'pizze', it: 'Focacce e pizze tonde', en: 'Focaccia and pizza',
  foto: '../img/w_foto_tonda_speck.jpg',
  gruppi: [
  { it: 'Le nostre focacce', en: 'Our focaccia', suffisso: '9', voci: [
    { it: 'Mortadella & stracciatella', en: 'Mortadella & stracciatella',
      dit: 'Mortadella, stracciatella, granella di pistacchio',
      den: 'Mortadella, stracciatella, chopped pistachio' },
    { it: 'Crudo & stracciatella', en: 'Prosciutto & stracciatella',
      dit: 'Prosciutto crudo, stracciatella, pesto',
      den: 'Cured ham, stracciatella, pesto' },
    { it: 'Salmone & bufala', en: 'Salmon & buffalo mozzarella',
      dit: 'Salmone, bufala, rucola', den: 'Salmon, buffalo mozzarella, rocket' },
    { it: 'La vegetariana', en: 'The vegetarian', dit: 'Scarola, broccoli, bufala',
      den: 'Escarole, broccoli, buffalo mozzarella' } ] },

  { it: 'Pizze tonde rosse', en: 'Red pizzas', voci: [
    { it: 'Marinara', en: 'Marinara', p: '8',
      dit: 'Pomodoro, aglio, origano, olio EVO',
      den: 'Tomato, garlic, oregano, olive oil' },
    { it: 'Margherita', en: 'Margherita', p: '9',
      dit: 'Pomodoro, mozzarella, basilico', den: 'Tomato, mozzarella, basil' },
    { it: 'Margherita con prosciutto cotto', en: 'Margherita with ham', p: '10' },
    { it: 'Margherita con funghi', en: 'Margherita with mushrooms', p: '10' },
    { it: 'Würstel e patatine', en: 'Frankfurters and chips', p: '11',
      dit: 'Pomodoro, mozzarella, würstel, patatine fritte',
      den: 'Tomato, mozzarella, frankfurters, chips' },
    { it: 'Napoli', en: 'Napoli', p: '11',
      dit: 'Pomodoro, mozzarella, alici, origano',
      den: 'Tomato, mozzarella, anchovies, oregano' },
    { it: 'Diavola', en: 'Diavola', p: '11',
      dit: 'Pomodoro, mozzarella, salame piccante',
      den: 'Tomato, mozzarella, spicy salami' },
    { it: 'Capricciosa', en: 'Capricciosa', p: '12',
      dit: 'Pomodoro, mozzarella, prosciutto cotto, funghi, olive, carciofi',
      den: 'Tomato, mozzarella, ham, mushrooms, olives, artichokes' },
    { it: 'Bufala e pachino', en: 'Buffalo and cherry tomato', p: '12',
      dit: 'Pomodoro, mozzarella di bufala, pomodorini, basilico',
      den: 'Tomato, buffalo mozzarella, cherry tomatoes, basil' },
    { it: 'Amatriciana', en: 'Amatriciana', p: '12',
      dit: 'Pomodoro, mozzarella, guanciale, pecorino, pepe',
      den: 'Tomato, mozzarella, guanciale, pecorino, pepper' } ] },

  { it: 'Pizze tonde bianche', en: 'White pizzas', voci: [
    { it: 'Crostino', en: 'Crostino', p: '11',
      dit: 'Mozzarella, prosciutto cotto', den: 'Mozzarella, cooked ham' },
    { it: 'Boscaiola', en: 'Boscaiola', p: '11',
      dit: 'Mozzarella, funghi, salsiccia', den: 'Mozzarella, mushrooms, sausage' },
    { it: 'Patate e salsiccia', en: 'Potato and sausage', p: '11' },
    { it: 'Fiori e alici', en: 'Courgette flowers and anchovies', p: '11',
      dit: 'Mozzarella, fiori di zucca, alici',
      den: 'Mozzarella, courgette flowers, anchovies' },
    { it: 'Cacio e pepe', en: 'Cacio e pepe', p: '11',
      dit: 'Crema di pecorino, pepe nero', den: 'Pecorino cream, black pepper' },
    { it: 'Vegetariana', en: 'Vegetarian', p: '11',
      dit: 'Mozzarella, verdure miste', den: 'Mozzarella, mixed vegetables' },
    { it: 'Porcini, provola e salsa marinara', en: 'Porcini, provola and marinara', p: '12' },
    { it: 'Carbonara', en: 'Carbonara', p: '12',
      dit: 'Mozzarella, guanciale, crema all’uovo, pecorino, pepe',
      den: 'Mozzarella, guanciale, egg cream, pecorino, pepper' },
    { it: 'Cesare', en: 'Caesar', p: '13',
      dit: 'Mozzarella, pollo grigliato, lattuga, salsa Caesar, grana',
      den: 'Mozzarella, grilled chicken, lettuce, Caesar dressing, grana' } ] },

  { it: '', en: '', formula: true, voci: [
    { it: 'Formula pizza', en: 'Pizza set', p: '15',
      dit: 'Pizza a scelta + supplì o crocchetta di patate + bibita (lattina o acqua)',
      den: 'Any pizza + a supplì or potato croquette + a drink (can or water)' } ] } ] },

/* ══ VIII  APERITIVO ══════════════════════════════════════════════════════ */
{ id: 'aperitivo', it: 'Aperitivo', en: 'Aperitivo',
  ore: '16:00 — 21:00', foto: '../img/w_foto_aperipizza.jpg',
  nota: { it: 'Ogni formula comprende una bevanda a scelta: cocktail classico, spritz, vino, birra o analcolica.',
          en: 'Every set includes a drink of your choice: classic cocktail, spritz, wine, beer or soft drink.' },
  gruppi: [ { evidenza: true, voci: [
    { it: 'Aperipizza', en: 'Aperipizza', p: '10',
      dit: 'Pizza al taglio e una bevanda', den: 'Pizza by the slice and a drink' },
    { it: 'Aperifritti', en: 'Aperifritti', p: '12',
      dit: 'Selezione di fritti caldi: supplì al telefono, crocchetta di patate, supplì carbonara o amatriciana',
      den: 'Hot fried selection: classic supplì, potato croquette, carbonara or amatriciana supplì' },
    { it: 'Happy hour', en: 'Happy hour', p: '12',
      dit: 'Tagliere misto di salumi, stuzzichini e pizza al taglio',
      den: 'Mixed cold cuts board, nibbles and pizza by the slice' },
    { it: 'Aperitagliere', en: 'Aperitagliere', p: '15',
      dit: 'Tagliere misto di salumi e formaggi, olive, sottoli, con una focaccia vuota',
      den: 'Mixed cold cuts and cheese board, olives, preserves, with a plain focaccia' } ] } ] },

/* ══ IX ══ COCKTAIL ═══════════════════════════════════════════════════════ */
{ id: 'cocktail', it: 'Cocktail', en: 'Cocktails', suffissoSezione: '7',
  gruppi: [ { suffisso: '7', voci: [
    { it: 'Aperol Spritz', en: 'Aperol Spritz', dit: 'Aperol, prosecco, soda, arancia',
      den: 'Aperol, prosecco, soda, orange' },
    { it: 'Campari Spritz', en: 'Campari Spritz', dit: 'Campari, prosecco, soda, arancia',
      den: 'Campari, prosecco, soda, orange' },
    { it: 'Hugo Spritz', en: 'Hugo Spritz',
      dit: 'Prosecco, sciroppo di sambuco, soda, menta, lime',
      den: 'Prosecco, elderflower, soda, mint, lime' },
    { it: 'Limoncello Spritz', en: 'Limoncello Spritz',
      dit: 'Limoncello, prosecco, soda, limone', den: 'Limoncello, prosecco, soda, lemon' },
    { it: 'Passion Spritz', en: 'Passion Spritz',
      dit: 'Prosecco, liquore al frutto della passione, soda, frutta fresca',
      den: 'Prosecco, passion fruit liqueur, soda, fresh fruit' },
    { it: 'Bellini', en: 'Bellini', dit: 'Prosecco, purea di pesca',
      den: 'Prosecco, peach purée' },
    { it: 'Mojito', en: 'Mojito', dit: 'Rum bianco, zucchero di canna, lime, menta, soda',
      den: 'White rum, cane sugar, lime, mint, soda' },
    { it: 'Mimosa', en: 'Mimosa', dit: 'Prosecco, succo d’arancia',
      den: 'Prosecco, orange juice' },
    { it: 'Rum & Cola', en: 'Rum & Cola', dit: 'Rum scuro, cola, lime',
      den: 'Dark rum, cola, lime' },
    { it: 'Caipiroska', en: 'Caipiroska', dit: 'Vodka, zucchero di canna, lime',
      den: 'Vodka, cane sugar, lime' },
    { it: 'Caipiroska alla fragola', en: 'Strawberry Caipiroska',
      dit: 'Vodka, lime, zucchero di canna, fragole fresche',
      den: 'Vodka, lime, cane sugar, fresh strawberries' },
    { it: 'Negroni', en: 'Negroni', dit: 'Gin, vermouth rosso, Campari',
      den: 'Gin, red vermouth, Campari' },
    { it: 'Negroni Sbagliato', en: 'Negroni Sbagliato',
      dit: 'Prosecco, vermouth rosso, Campari', den: 'Prosecco, red vermouth, Campari' },
    { it: 'Americano', en: 'Americano', dit: 'Campari, vermouth rosso, soda',
      den: 'Campari, red vermouth, soda' },
    { it: 'Gin Tonic', en: 'Gin & Tonic', dit: 'Gin, acqua tonica, lime o limone',
      den: 'Gin, tonic water, lime or lemon' },
    { it: 'Moscow Mule', en: 'Moscow Mule', dit: 'Vodka, ginger beer, succo di lime',
      den: 'Vodka, ginger beer, lime juice' },
    { it: 'Bailey Martini', en: 'Bailey Martini', dit: 'Vodka, Baileys', den: 'Vodka, Baileys' },
    { it: 'Malibu & Cola', en: 'Malibu & Cola', dit: 'Malibu, cola, lime',
      den: 'Malibu, cola, lime' } ] } ] },

/* ══ X ═══ BEVANDE ════════════════════════════════════════════════════════ */
{ id: 'bevande', it: 'Bevande', en: 'Drinks',
  gruppi: [ { fitto: true, voci: [
    { it: 'Acqua 0,5 L', en: 'Water 0.5 L', p: '1,50' },
    { it: 'Acqua 0,75 L', en: 'Water 0.75 L', p: '3,00' },
    { it: 'Succhi di frutta', en: 'Fruit juice', p: '3,00' },
    { it: 'Tè alla pesca o limone', en: 'Peach or lemon iced tea', p: '3,00' },
    { it: 'Tè della casa', en: 'House iced tea', p: '2,50' },
    { it: 'Spremuta d’arancia', en: 'Fresh orange juice', p: '4,00' },
    { it: 'Spremuta di pompelmo', en: 'Fresh grapefruit juice', p: '4,00' },
    { it: 'Coca-Cola, Fanta, Sprite', en: 'Coca-Cola, Fanta, Sprite', p: '3,00' },
    { it: 'Chinotto', en: 'Chinotto', p: '3,00' },
    { it: 'Schweppes limone', en: 'Schweppes lemon', p: '3,50' },
    { it: 'Schweppes tonica', en: 'Schweppes tonic', p: '3,50' },
    { it: 'Red Bull', en: 'Red Bull', p: '3,50',
      dit: 'Energy drink, Zero, Pink Edition', den: 'Energy drink, Zero, Pink Edition' },
    { it: 'Crodino', en: 'Crodino', p: '3,50' },
    { it: 'Campari Soda', en: 'Campari Soda', p: '3,50' },
    { it: 'Campari Soda corretto', en: 'Campari Soda with a shot', p: '3,90' },
    { it: 'Corona', en: 'Corona', p: '4,00' },
    { it: 'Corona 0', en: 'Corona 0', p: '4,00' },
    { it: 'Messina 33 cl', en: 'Messina 33 cl', p: '4,00' },
    { it: 'Ichnusa non filtrata', en: 'Ichnusa unfiltered', p: '4,00' },
    { it: 'Birra alla spina', en: 'Draught beer', p: '6,00',
      dit: 'Heineken o Moretti', den: 'Heineken or Moretti' },
    { it: 'Calice di Prosecco', en: 'Glass of Prosecco', p: '6,00' },
    { it: 'Calice di vino bianco', en: 'Glass of white wine', p: '6,00' },
    { it: 'Calice di vino rosso', en: 'Glass of red wine', p: '6,00' },
    { it: 'Amari', en: 'Amaro', p: '4,00' },
    { it: 'Whisky', en: 'Whisky', p: '4,00' } ] } ] },

/* ══ XI ══ AL TAGLIO (108) ════════════════════════════════════════════════ */
{ id: 'taglio', it: 'Pizza al taglio', en: 'Pizza by the slice',
  ore: { it: 'TUTTO IL GIORNO · MERULANA 108', en: 'ALL DAY · MERULANA 108' },
  foto: '../img/w_foto_tranci.jpg',
  nota: { it: 'Due porte più in là, al 108. Prezzo al trancio. Pizze tonde da asporto su ordinazione.',
          en: 'Two doors down, at number 108. Price per slice. Round pizzas to take away, on order.' },
  gruppi: [ { voci: [
    { it: 'Bianca', en: 'White', p: '2,50' },
    { it: 'Rossa, Marinara, Patate', en: 'Tomato, Marinara, Potato', p: '4,00' },
    { it: 'Margherita', en: 'Margherita', p: '4,50' },
    { it: 'Crostini', en: 'Crostini', p: '5,00' },
    { it: 'Speciali', en: 'Speciality', p: '6,00' },
    { it: 'Ripiene', en: 'Filled', p: '6,00' },
    { it: 'Calzoni', en: 'Calzoni', p: '5,00' },
    { it: 'Bibita in lattina', en: 'Canned drink', p: '3,50' } ] } ] }

];
