/* ───────────────────────────────────────────────────────────────────────────
   MERA BISTROT — i dati del menù.

   Questo è l'unico file da toccare per cambiare piatti, prezzi o traduzioni.
   La pagina (menu.html) non va mai modificata per un cambio di listino.

   Ogni voce:  { it:'nome italiano', en:'english name',
                 dit:'descrizione',  den:'description',   // facoltative
                 p:'11' }                                  // prezzo, senza €

   Contenuto trascritto dal menù in uso (digitalmenucheck.com, 11 pagine).
   ─────────────────────────────────────────────────────────────────────────── */

const LOCALE = {
  nome: 'Mera Bistrot',
  via: 'Via Merulana 106/107 · Roma',
  taglio: 'Via Merulana 108',
  tel: '+390686299500', telLabel: '06 86299500',
  wa: '39375910047', waLabel: '375 910047',
  orari: { it: 'Tutti i giorni 7:30 — 22:00', en: 'Every day 7:30 — 22:00', es: 'Todos los días 7:30 — 22:00' },
  // password vuota: la targa Wi-Fi non compare affatto, invece di mostrare
  // un segnaposto ai clienti. Appena c'e', si scrive qui e riappare.
  wifi: { rete: 'Mera Bistrot', pass: '' },
  recensioni: {
    google: 'https://www.google.com/maps/search/?api=1&query=MERA%20Bistrot%20%26%20Cafe%27&query_place_id=ChIJcVcAfiRhLxMROKVtWWs08YQ',
    tripadvisor: 'https://www.tripadvisor.it/'
  },
  mappa: 'https://maps.google.com/?q=Via+Merulana+106,+Roma'
};

const SEZIONI = [

/* ══ I ═══ COLAZIONE ══════════════════════════════════════════════════════ */
{ id: 'colazione', it: 'Colazione', en: 'Breakfast', es: 'Desayuno',
  ore: '8:40 — 16:00', foto: '../img/w_foto_colazione.jpg',
  nota: { it: 'Servita fino alle 16:00, anche nel pomeriggio.',
          en: 'Served until 16:00, afternoons included.', es: 'Servido hasta las 16:00, también por la tarde.' },
  gruppi: [
  { it: 'Dolci', en: 'Sweet', es: 'Dulces', voci: [
    { it: 'Macedonia di frutta', en: 'Fruit salad', es: 'Macedonia de frutas', p: '5' },
    { it: 'Waffle', en: 'Waffle', es: 'Gofre', p: '8',
      dit: 'Nutella o sciroppo d’acero, frutta fresca',
      den: 'Nutella or maple syrup, fresh fruit', des: 'Nutella o sirope de arce, fruta fresca' },
    { it: 'Porridge', en: 'Porridge', es: 'Porridge', p: '9',
      dit: 'Fiocchi d’avena cotti in acqua o latte, con frutta fresca',
      den: 'Oats cooked in water or milk, with fresh fruit', des: 'Copos de avena cocidos en agua o leche, con fruta fresca' },
    { it: 'Pancake', en: 'Pancakes', es: 'Tortitas', p: '9',
      dit: 'Nutella o sciroppo d’acero, frutta fresca',
      den: 'Nutella or maple syrup, fresh fruit', des: 'Nutella o sirope de arce, fruta fresca' },
    { it: 'Bowl di yogurt', en: 'Yogurt bowl', es: 'Bol de yogur', p: '9',
      dit: 'Yogurt cremoso con granola e frutta fresca',
      den: 'Creamy yogurt with granola and fresh fruit', des: 'Yogur cremoso con granola y fruta fresca' } ] },

  { it: 'Salate', en: 'Savoury', es: 'Saladas', voci: [
    { it: 'Toast cotto', en: 'Ham toastie', es: 'Tostado de jamón cocido', p: '8',
      dit: 'Prosciutto cotto, insalata e bufala',
      den: 'Cooked ham, lettuce and buffalo mozzarella', des: 'Jamón cocido, lechuga y mozzarella de búfala' },
    { it: 'Toast crudo', en: 'Prosciutto toastie', es: 'Tostado de jamón serrano', p: '8',
      dit: 'Prosciutto crudo, insalata e stracciatella',
      den: 'Cured ham, lettuce and stracciatella', des: 'Jamón serrano, lechuga y stracciatella' },
    { it: 'Toast al salmone', en: 'Salmon toastie', es: 'Tostado de salmón', p: '10',
      dit: 'Salmone affumicato, crema al formaggio e avocado',
      den: 'Smoked salmon, cream cheese and avocado', des: 'Salmón ahumado, queso crema y aguacate' },
    { it: 'Uova strapazzate con bacon', en: 'Scrambled eggs with bacon', es: 'Huevos revueltos con bacon', p: '11',
      dit: 'Pane bruscato e insalata', den: 'Toasted bread and salad', des: 'Pan tostado y ensalada' },
    { it: 'Uova strapazzate con würstel', en: 'Scrambled eggs with frankfurters', es: 'Huevos revueltos con salchichas', p: '11',
      dit: 'Pane bruscato e insalata', den: 'Toasted bread and salad', des: 'Pan tostado y ensalada' },
    { it: 'Omelette vegetariana', en: 'Vegetarian omelette', es: 'Tortilla vegetariana', p: '12',
      dit: 'Uova, zucchine, parmigiano', den: 'Eggs, courgettes, parmesan', des: 'Huevo, calabacín y parmesano' },
    { it: 'Omelette classica', en: 'Classic omelette', es: 'Tortilla clásica', p: '12',
      dit: 'Uova, prosciutto cotto, cheddar e bacon',
      den: 'Eggs, cooked ham, cheddar and bacon', des: 'Huevo, jamón cocido, cheddar y bacon' },
    { it: 'Maxi club sandwich classic', en: 'Maxi club sandwich', es: 'Maxi club sandwich', p: '15',
      dit: 'Pane tostato, prosciutto cotto, uova, bacon croccante, lattuga, pomodoro, maionese, cheddar',
      den: 'Toasted bread, cooked ham, egg, crispy bacon, lettuce, tomato, mayo, cheddar', des: 'Pan tostado, jamón cocido, huevo, bacon crujiente, lechuga, tomate, mayonesa y cheddar' } ] },

  { it: 'Formule colazione', en: 'Breakfast sets', es: 'Fórmulas desayuno', evidenza: true, voci: [
    { it: 'All’Italiana', en: 'The Italian one', es: 'A la italiana', p: '9',
      dit: 'Torta del giorno o crostata + spremuta d’arancia + caffè o cappuccino',
      den: 'Cake of the day or tart + orange juice + coffee or cappuccino', des: 'Tarta del día o tarta de mermelada + zumo de naranja + café o capuchino' },
    { it: 'Dolce', en: 'Sweet', es: 'Dulce', p: '13',
      dit: 'Dolce a scelta + spremuta d’arancia + caffè o cappuccino',
      den: 'Any sweet dish + orange juice + coffee or cappuccino', des: 'Un dulce a elegir + zumo de naranja + café o capuchino' },
    { it: 'Salata', en: 'Savoury', es: 'Salada', p: '16',
      dit: 'Colazione salata a scelta (escluso maxi club sandwich) + spremuta + caffè o cappuccino',
      den: 'Any savoury dish (maxi club sandwich excluded) + juice + coffee or cappuccino', des: 'Un salado a elegir (maxi club sandwich excluido) + zumo + café o capuchino' },
    { it: 'Maxi club sandwich', en: 'Maxi club sandwich set', es: 'Maxi club sandwich', p: '19',
      dit: 'Spremuta d’arancia + caffè o cappuccino',
      den: 'Orange juice + coffee or cappuccino', des: 'Zumo de naranja + café o capuchino' },
    { it: 'Macedonia', en: 'Fruit salad set', es: 'Macedonia', p: '10',
      dit: 'Spremuta d’arancia + caffè o cappuccino',
      den: 'Orange juice + coffee or cappuccino', des: 'Zumo de naranja + café o capuchino' } ] } ] },

/* ══ II ══ CAFFETTERIA ════════════════════════════════════════════════════ */
{ id: 'caffetteria', it: 'Caffetteria', en: 'Coffee bar', es: 'Cafetería',
  ore: { it: 'TUTTO IL GIORNO', en: 'ALL DAY', es: 'TODO EL DÍA' },
  gruppi: [
  { it: 'Al banco', en: 'At the counter', es: 'En la barra', fitto: true, voci: [
    { it: 'Caffè', en: 'Espresso', es: 'Café', p: '1,70' },
    { it: 'Caffè decaffeinato', en: 'Decaf espresso', es: 'Café descafeinado', p: '1,80' },
    { it: 'Caffè latte', en: 'Latte', es: 'Café con leche', p: '2,20' },
    { it: 'Caffè freddo', en: 'Iced coffee', es: 'Café frío', p: '2,20' },
    { it: 'Caffè corretto', en: 'Espresso with a shot', es: 'Carajillo', p: '2,80' },
    { it: 'Caffè doppio', en: 'Double espresso', es: 'Café doble', p: '3,00' },
    { it: 'Latte bianco', en: 'Warm milk', es: 'Leche caliente', p: '1,90' },
    { it: 'Cappuccino', en: 'Cappuccino', es: 'Capuchino', p: '2,00' },
    { it: 'Cappuccino freddo', en: 'Iced cappuccino', es: 'Capuchino frío', p: '2,00' },
    { it: 'Cappuccino deca o senza lattosio', en: 'Decaf or lactose-free cappuccino', es: 'Capuchino descafeinado o sin lactosa', p: '2,20' },
    { it: 'Cappuccino orzo o ginseng', en: 'Barley or ginseng cappuccino', es: 'Capuchino de cebada o ginseng', p: '2,40' },
    { it: 'Cappuccino grande', en: 'Large cappuccino', es: 'Capuchino grande', p: '3,40' },
    { it: 'Orzo piccolo', en: 'Barley coffee, small', es: 'Cebada, pequeño', p: '1,90' },
    { it: 'Orzo grande', en: 'Barley coffee, large', es: 'Cebada, grande', p: '2,40' },
    { it: 'Ginseng piccolo', en: 'Ginseng coffee, small', es: 'Ginseng, pequeño', p: '1,90' },
    { it: 'Ginseng grande', en: 'Ginseng coffee, large', es: 'Ginseng, grande', p: '2,40' },
    { it: 'Marocchino', en: 'Marocchino', es: 'Marocchino', p: '2,10' },
    { it: 'Americano', en: 'Americano', es: 'Americano', p: '2,40' },
    { it: 'Americano grande', en: 'Large americano', es: 'Americano grande', p: '3,40' },
    { it: 'Tè caldo', en: 'Hot tea', es: 'Té caliente', p: '2,50' },
    { it: 'Crema di caffè', en: 'Coffee cream', es: 'Crema de café', p: '4,00' },
    { it: 'Cioccolata calda', en: 'Hot chocolate', es: 'Chocolate caliente', p: '4,00' } ] },

  { it: 'Cornetti e dolci da forno', en: 'Pastries', es: 'Bollería', fitto: true, voci: [
    { it: 'Cornetti mignon', en: 'Mini croissants', es: 'Mini cruasanes', p: '1,10' },
    { it: 'Cornetto classico', en: 'Plain croissant', es: 'Cruasán clásico', p: '1,80' },
    { it: 'Cornetti farciti', en: 'Filled croissants', es: 'Cruasanes rellenos', p: '2,00',
      dit: 'Crema, albicocca, visciole, cioccolato',
      den: 'Custard, apricot, sour cherry, chocolate', des: 'Crema, albaricoque, guinda, chocolate' },
    { it: 'Ciambelle e bombe classiche', en: 'Plain doughnuts', es: 'Donuts clásicos', p: '2,20' },
    { it: 'Ciambelle e bombe farcite', en: 'Filled doughnuts', es: 'Donuts rellenos', p: '4,00',
      dit: 'Pistacchio, albicocca, visciole, cioccolato e frutta',
      den: 'Pistachio, apricot, sour cherry, chocolate and fruit', des: 'Pistacho, albaricoque, guinda, chocolate y fruta' },
    { it: 'Ciambellone', en: 'Ring cake', es: 'Bizcocho', p: '3,20' },
    { it: 'Crostata', en: 'Jam tart', es: 'Tarta de mermelada', p: '4,00' },
    { it: 'Torta del giorno', en: 'Cake of the day', es: 'Tarta del día', p: '5,00' } ] },

  { it: 'Centrifughe', en: 'Juices', es: 'Zumos naturales', suffisso: '6', voci: [
    { it: 'Dissetante', en: 'Refreshing', es: 'Refrescante', dit: 'Mela, limone, zenzero',
      den: 'Apple, lemon, ginger', des: 'Manzana, limón, jengibre' },
    { it: 'Drenante', en: 'Draining', es: 'Drenante', dit: 'Pompelmo, cetriolo, finocchio',
      den: 'Grapefruit, cucumber, fennel', des: 'Pomelo, pepino, hinojo' },
    { it: 'Depurativa', en: 'Cleansing', es: 'Depurativa', dit: 'Kiwi, sedano, melone, zenzero',
      den: 'Kiwi, celery, melon, ginger', des: 'Kiwi, apio, melón, jengibre' },
    { it: 'Vitamina A-C', en: 'Vitamin A-C', es: 'Vitamina A-C', dit: 'Carota, mango, arancia',
      den: 'Carrot, mango, orange', des: 'Zanahoria, mango, naranja' },
    { it: 'Detox', en: 'Detox', es: 'Detox', dit: 'Carota, sedano, finocchio',
      den: 'Carrot, celery, fennel', des: 'Zanahoria, apio, hinojo' },
    { it: 'A scelta', en: 'Your own', es: 'A tu gusto', dit: 'Con 3 frutti della lista',
      den: 'With 3 items from the list above', des: 'Con 3 frutas de la lista' } ] } ] },

/* ══ III ═ ANTIPASTI ══════════════════════════════════════════════════════ */
{ id: 'antipasti', it: 'Antipasti', en: 'Starters', es: 'Entrantes',
  gruppi: [ { voci: [
    { it: 'Supplì al telefono', en: 'Classic supplì', es: 'Supplì clásico', p: '2,20' },
    { it: 'Crocchetta di patate', en: 'Potato croquette', es: 'Croqueta de patata', p: '2,20' },
    { it: 'Supplì alla carbonara', en: 'Carbonara supplì', es: 'Supplì a la carbonara', p: '3' },
    { it: 'Supplì all’amatriciana', en: 'Amatriciana supplì', es: 'Supplì a la amatriciana', p: '3' },
    { it: 'Bruschetta al pomodoro', en: 'Tomato bruschetta', es: 'Bruschetta de tomate', p: '4',
      dit: '2 pezzi', den: '2 pieces', des: '2 piezas' },
    { it: 'Bruschetta al pesto', en: 'Pesto bruschetta', es: 'Bruschetta al pesto', p: '5',
      dit: 'Con pomodorini confit · 2 pezzi', den: 'With confit cherry tomatoes · 2 pieces', des: 'Con tomates confitados · 2 piezas' },
    { it: 'Bruschetta stracciatella e alici', en: 'Stracciatella and anchovy bruschetta', es: 'Bruschetta de stracciatella y anchoas', p: '6',
      dit: '2 pezzi', den: '2 pieces', des: '2 piezas' },
    { it: 'Bruschetta salmone e stracciatella', en: 'Salmon and stracciatella bruschetta', es: 'Bruschetta de salmón y stracciatella', p: '6',
      dit: '2 pezzi', den: '2 pieces', des: '2 piezas' },
    { it: 'Tris di bruschette', en: 'Three bruschette', es: 'Trío de bruschettas', p: '8' },
    { it: 'Caprese', en: 'Caprese', es: 'Caprese', p: '9' },
    { it: 'Crudo e bufala', en: 'Prosciutto and buffalo mozzarella', es: 'Jamón serrano y mozzarella de búfala', p: '13',
      dit: 'Accompagnati da una focaccia', den: 'Served with a focaccia', des: 'Acompañados de una focaccia' },
    { it: 'Tagliere di salumi', en: 'Cold cuts board', es: 'Tabla de embutidos', p: '22',
      dit: 'Con 2 focacce e mozzarella di bufala, per due persone',
      den: 'With 2 focacce and buffalo mozzarella, for two', des: 'Con 2 focaccias y mozzarella de búfala, para dos personas' } ] } ] },

/* ══ IV ══ PRIMI ══════════════════════════════════════════════════════════ */
{ id: 'primi', it: 'Primi piatti', en: 'Pasta', es: 'Primeros',
  gruppi: [ { voci: [
    { it: 'Tonnarelli alla carbonara', en: 'Tonnarelli carbonara', es: 'Tonnarelli a la carbonara', p: '11' },
    { it: 'Tonnarelli all’amatriciana', en: 'Tonnarelli amatriciana', es: 'Tonnarelli a la amatriciana', p: '11' },
    { it: 'Tonnarelli cacio e pepe', en: 'Tonnarelli cacio e pepe', es: 'Tonnarelli cacio e pepe', p: '11' },
    { it: 'Tonnarelli alla gricia', en: 'Tonnarelli gricia', es: 'Tonnarelli a la gricia', p: '11' },
    { it: 'Penne al pomodoro e basilico', en: 'Penne with tomato and basil', es: 'Penne con tomate y albahaca', p: '10' },
    { it: 'Lasagna alla bolognese', en: 'Lasagne bolognese', es: 'Lasaña a la boloñesa', p: '11' },
    { it: 'Fettuccine al ragù di manzo', en: 'Fettuccine with beef ragù', es: 'Fettuccine con ragú de ternera', p: '11' },
    { it: 'Fettuccine Alfredo', en: 'Fettuccine Alfredo', es: 'Fettuccine Alfredo', p: '10' },
    { it: 'Fettuccine ai funghi porcini', en: 'Fettuccine with porcini', es: 'Fettuccine con boletus', p: '12' },
    { it: 'Fettuccine al salmone', en: 'Fettuccine with salmon', es: 'Fettuccine con salmón', p: '13' } ] } ] },

/* ══ V ═══ SECONDI ════════════════════════════════════════════════════════ */
{ id: 'secondi', it: 'Secondi e contorni', en: 'Mains and sides', es: 'Segundos y guarniciones',
  gruppi: [
  { it: 'Secondi', en: 'Mains', es: 'Segundos', voci: [
    { it: 'Polpette al sugo', en: 'Meatballs in tomato sauce', es: 'Albóndigas en salsa de tomate', p: '8',
      dit: 'Morbide polpette di manzo nel sugo di pomodoro · 5 pezzi',
      den: 'Soft beef meatballs in tomato sauce · 5 pieces', des: 'Albóndigas tiernas de ternera en salsa de tomate · 5 piezas' },
    { it: 'Polpette all’amatriciana', en: 'Amatriciana meatballs', es: 'Albóndigas a la amatriciana', p: '10',
      dit: 'Polpette di manzo con guanciale in salsa all’amatriciana · 5 pezzi',
      den: 'Beef meatballs with guanciale in amatriciana sauce · 5 pieces', des: 'Albóndigas de ternera con guanciale en salsa amatriciana · 5 piezas' },
    { it: 'Polpette ai funghi porcini', en: 'Meatballs with porcini', es: 'Albóndigas con boletus', p: '10',
      dit: 'Polpette di manzo in salsa ai funghi porcini · 5 pezzi',
      den: 'Beef meatballs in porcini sauce · 5 pieces', des: 'Albóndigas de ternera en salsa de boletus · 5 piezas' },
    { it: 'Polpette al ragù', en: 'Meatballs in ragù', es: 'Albóndigas al ragú', p: '10',
      dit: 'Morbide polpette con salsa al ragù · 5 pezzi',
      den: 'Soft meatballs in ragù · 5 pieces', des: 'Albóndigas tiernas con salsa de ragú · 5 piezas' },
    { it: 'Hamburger al piatto', en: 'Beef patty, no bun', es: 'Hamburguesa sin pan', p: '11' },
    { it: 'Cotoletta di pollo', en: 'Breaded chicken cutlet', es: 'Escalope de pollo', p: '9' },
    { it: 'Thai di pollo con verdure', en: 'Thai chicken with vegetables', es: 'Pollo thai con verduras', p: '10' },
    { it: 'Tagliata di pollo', en: 'Sliced chicken', es: 'Pollo en tiras', p: '13',
      dit: 'Pomodori confit, grana, salsa all’aceto balsamico',
      den: 'Confit tomatoes, grana, balsamic dressing', des: 'Tomates confitados, grana y salsa de vinagre balsámico' } ] },

  { it: 'Contorni', en: 'Sides', es: 'Guarniciones', suffisso: '5', voci: [
    { it: 'Patate al forno', en: 'Roast potatoes', es: 'Patatas al horno' },
    { it: 'Patatine fritte', en: 'Chips', es: 'Patatas fritas' },
    { it: 'Cicoria alla romana', en: 'Roman chicory', es: 'Achicoria a la romana' },
    { it: 'Scarola', en: 'Escarole', es: 'Escarola' },
    { it: 'Broccoli', en: 'Broccoli', es: 'Brócoli' } ] } ] },

/* ══ VI ══ INSALATONE E HAMBURGER ═════════════════════════════════════════ */
{ id: 'insalate', it: 'Insalatone e hamburger', en: 'Salads and burgers', es: 'Ensaladas y hamburguesas',
  gruppi: [
  { it: 'Insalatone', en: 'Big salads', es: 'Ensaladas', voci: [
    { it: 'Mera', en: 'Mera', es: 'Mera', p: '11',
      dit: 'Lattuga, rughetta, pomodorini confit, tonno, olive nere, noci',
      den: 'Lettuce, rocket, confit tomatoes, tuna, black olives, walnuts', des: 'Lechuga, rúcula, tomates confitados, atún, aceitunas negras y nueces' },
    { it: 'Classica', en: 'Classic', es: 'Clásica', p: '9',
      dit: 'Lattuga, pomodorini, cetrioli, carote, cipolla rossa, olive nere',
      den: 'Lettuce, cherry tomatoes, cucumber, carrot, red onion, black olives', des: 'Lechuga, tomate cherry, pepino, zanahoria, cebolla roja y aceitunas negras' },
    { it: 'Caesar', en: 'Caesar', es: 'César', p: '12',
      dit: 'Lattuga, pollo grigliato, crostini, scaglie di grana, salsa Caesar',
      den: 'Lettuce, grilled chicken, croutons, grana shavings, Caesar dressing', des: 'Lechuga, pollo a la plancha, picatostes, lascas de grana y salsa César' },
    { it: 'Salmone', en: 'Salmon', es: 'Salmón', p: '12',
      dit: 'Lattuga, salmone affumicato, avocado, cetrioli, pomodorini, semi di sesamo, salsa teriyaki',
      den: 'Lettuce, smoked salmon, avocado, cucumber, tomatoes, sesame, teriyaki', des: 'Lechuga, salmón ahumado, aguacate, pepino, tomate cherry, sésamo y salsa teriyaki' } ] },

  { it: 'Hamburger', en: 'Burgers', es: 'Hamburguesas', voci: [
    { it: 'Classico', en: 'Classic', es: 'Clásica', p: '13',
      dit: 'Hamburger di manzo, lattuga, pomodoro, pane morbido + patatine fritte',
      den: 'Beef patty, lettuce, tomato, soft bun + chips', des: 'Hamburguesa de ternera, lechuga, tomate, pan brioche + patatas fritas' },
    { it: 'Cheeseburger', en: 'Cheeseburger', es: 'Cheeseburger', p: '14',
      dit: 'Hamburger di manzo, cheddar, lattuga, pomodoro, pane morbido + patatine fritte',
      den: 'Beef patty, cheddar, lettuce, tomato, soft bun + chips', des: 'Hamburguesa de ternera, cheddar, lechuga, tomate, pan brioche + patatas fritas' },
    { it: 'Cheesebaconburger', en: 'Cheese and bacon burger', es: 'Cheesebaconburger', p: '15',
      dit: 'Hamburger di manzo, cheddar, bacon croccante, lattuga, pomodoro, pane morbido + patatine fritte',
      den: 'Beef patty, cheddar, crispy bacon, lettuce, tomato, soft bun + chips', des: 'Hamburguesa de ternera, cheddar, bacon crujiente, lechuga, tomate, pan brioche + patatas fritas' } ] },

  { it: '', en: '', es: '', formula: true, voci: [
    { it: 'Formula hamburger', en: 'Burger set', es: 'Fórmula hamburguesa', p: '16',
      dit: 'Hamburger a scelta + contorno + bevanda',
      den: 'Any burger + a side + a drink', des: 'Hamburguesa a elegir + guarnición + bebida' } ] } ] },

/* ══ VII ═ PIZZE ══════════════════════════════════════════════════════════ */
{ id: 'pizze', it: 'Focacce e pizze tonde', en: 'Focaccia and pizza', es: 'Focaccias y pizzas',
  foto: '../img/w_foto_tonda_speck.jpg',
  gruppi: [
  { it: 'Le nostre focacce', en: 'Our focaccia', es: 'Nuestras focaccias', suffisso: '9', voci: [
    { it: 'Mortadella & stracciatella', en: 'Mortadella & stracciatella', es: 'Mortadela y stracciatella',
      dit: 'Mortadella, stracciatella, granella di pistacchio',
      den: 'Mortadella, stracciatella, chopped pistachio', des: 'Mortadela, stracciatella y pistacho picado' },
    { it: 'Crudo & stracciatella', en: 'Prosciutto & stracciatella', es: 'Jamón serrano y stracciatella',
      dit: 'Prosciutto crudo, stracciatella, pesto',
      den: 'Cured ham, stracciatella, pesto', des: 'Jamón serrano, stracciatella y pesto' },
    { it: 'Salmone & bufala', en: 'Salmon & buffalo mozzarella', es: 'Salmón y mozzarella de búfala',
      dit: 'Salmone, bufala, rucola', den: 'Salmon, buffalo mozzarella, rocket', des: 'Salmón, mozzarella de búfala y rúcula' },
    { it: 'La vegetariana', en: 'The vegetarian', es: 'La vegetariana', dit: 'Scarola, broccoli, bufala',
      den: 'Escarole, broccoli, buffalo mozzarella', des: 'Escarola, brócoli y mozzarella de búfala' } ] },

  { it: 'Pizze tonde rosse', en: 'Red pizzas', es: 'Pizzas rojas', voci: [
    { it: 'Marinara', en: 'Marinara', es: 'Marinara', p: '8',
      dit: 'Pomodoro, aglio, origano, olio EVO',
      den: 'Tomato, garlic, oregano, olive oil', des: 'Tomate, ajo, orégano y aceite de oliva' },
    { it: 'Margherita', en: 'Margherita', es: 'Margherita', p: '9',
      dit: 'Pomodoro, mozzarella, basilico', den: 'Tomato, mozzarella, basil', des: 'Tomate, mozzarella y albahaca' },
    { it: 'Margherita con prosciutto cotto', en: 'Margherita with ham', es: 'Margherita con jamón cocido', p: '10' },
    { it: 'Margherita con funghi', en: 'Margherita with mushrooms', es: 'Margherita con champiñones', p: '10' },
    { it: 'Würstel e patatine', en: 'Frankfurters and chips', es: 'Salchichas y patatas fritas', p: '11',
      dit: 'Pomodoro, mozzarella, würstel, patatine fritte',
      den: 'Tomato, mozzarella, frankfurters, chips', des: 'Tomate, mozzarella, salchichas y patatas fritas' },
    { it: 'Napoli', en: 'Napoli', es: 'Nápoles', p: '11',
      dit: 'Pomodoro, mozzarella, alici, origano',
      den: 'Tomato, mozzarella, anchovies, oregano', des: 'Tomate, mozzarella, anchoas y orégano' },
    { it: 'Diavola', en: 'Diavola', es: 'Diavola', p: '11',
      dit: 'Pomodoro, mozzarella, salame piccante',
      den: 'Tomato, mozzarella, spicy salami', des: 'Tomate, mozzarella y salami picante' },
    { it: 'Capricciosa', en: 'Capricciosa', es: 'Capricciosa', p: '12',
      dit: 'Pomodoro, mozzarella, prosciutto cotto, funghi, olive, carciofi',
      den: 'Tomato, mozzarella, ham, mushrooms, olives, artichokes', des: 'Tomate, mozzarella, jamón cocido, champiñones, aceitunas y alcachofas' },
    { it: 'Bufala e pachino', en: 'Buffalo and cherry tomato', es: 'Búfala y tomate cherry', p: '12',
      dit: 'Pomodoro, mozzarella di bufala, pomodorini, basilico',
      den: 'Tomato, buffalo mozzarella, cherry tomatoes, basil', des: 'Tomate, mozzarella de búfala, tomate cherry y albahaca' },
    { it: 'Amatriciana', en: 'Amatriciana', es: 'Amatriciana', p: '12',
      dit: 'Pomodoro, mozzarella, guanciale, pecorino, pepe',
      den: 'Tomato, mozzarella, guanciale, pecorino, pepper', des: 'Tomate, mozzarella, guanciale, pecorino y pimienta' } ] },

  { it: 'Pizze tonde bianche', en: 'White pizzas', es: 'Pizzas blancas', voci: [
    { it: 'Crostino', en: 'Crostino', es: 'Crostino', p: '11',
      dit: 'Mozzarella, prosciutto cotto', den: 'Mozzarella, cooked ham', des: 'Mozzarella y jamón cocido' },
    { it: 'Boscaiola', en: 'Boscaiola', es: 'Boscaiola', p: '11',
      dit: 'Mozzarella, funghi, salsiccia', den: 'Mozzarella, mushrooms, sausage', des: 'Mozzarella, champiñones y salchicha' },
    { it: 'Patate e salsiccia', en: 'Potato and sausage', es: 'Patata y salchicha', p: '11' },
    { it: 'Fiori e alici', en: 'Courgette flowers and anchovies', es: 'Flor de calabacín y anchoas', p: '11',
      dit: 'Mozzarella, fiori di zucca, alici',
      den: 'Mozzarella, courgette flowers, anchovies', des: 'Mozzarella, flor de calabacín y anchoas' },
    { it: 'Cacio e pepe', en: 'Cacio e pepe', es: 'Cacio e pepe', p: '11',
      dit: 'Crema di pecorino, pepe nero', den: 'Pecorino cream, black pepper', des: 'Crema de pecorino y pimienta negra' },
    { it: 'Vegetariana', en: 'Vegetarian', es: 'Vegetariana', p: '11',
      dit: 'Mozzarella, verdure miste', den: 'Mozzarella, mixed vegetables', des: 'Mozzarella y verduras variadas' },
    { it: 'Porcini, provola e salsa marinara', en: 'Porcini, provola and marinara', es: 'Boletus, provola y salsa marinara', p: '12' },
    { it: 'Carbonara', en: 'Carbonara', es: 'Carbonara', p: '12',
      dit: 'Mozzarella, guanciale, crema all’uovo, pecorino, pepe',
      den: 'Mozzarella, guanciale, egg cream, pecorino, pepper', des: 'Mozzarella, guanciale, crema de huevo, pecorino y pimienta' },
    { it: 'Cesare', en: 'Caesar', es: 'César', p: '13',
      dit: 'Mozzarella, pollo grigliato, lattuga, salsa Caesar, grana',
      den: 'Mozzarella, grilled chicken, lettuce, Caesar dressing, grana', des: 'Mozzarella, pollo a la plancha, lechuga, salsa César y grana' } ] },

  { it: '', en: '', es: '', formula: true, voci: [
    { it: 'Formula pizza', en: 'Pizza set', es: 'Fórmula pizza', p: '15',
      dit: 'Pizza a scelta + supplì o crocchetta di patate + bibita (lattina o acqua)',
      den: 'Any pizza + a supplì or potato croquette + a drink (can or water)', des: 'Pizza a elegir + supplì o croqueta de patata + bebida (lata o agua)' } ] } ] },

/* ══ VIII  APERITIVO ══════════════════════════════════════════════════════ */
{ id: 'aperitivo', it: 'Aperitivo', en: 'Aperitivo', es: 'Aperitivo',
  ore: '16:00 — 21:00', foto: '../img/w_foto_aperipizza.jpg',
  nota: { it: 'Ogni formula comprende una bevanda a scelta: cocktail classico, spritz, vino, birra o analcolica.',
          en: 'Every set includes a drink of your choice: classic cocktail, spritz, wine, beer or soft drink.', es: 'Cada fórmula incluye una bebida a elegir: cóctel clásico, spritz, vino, cerveza o refresco.' },
  gruppi: [ { evidenza: true, voci: [
    { it: 'Aperipizza', en: 'Aperipizza', es: 'Aperipizza', p: '10',
      dit: 'Pizza al taglio e una bevanda', den: 'Pizza by the slice and a drink', des: 'Pizza al corte y una bebida' },
    { it: 'Aperifritti', en: 'Aperifritti', es: 'Aperifritti', p: '12',
      dit: 'Selezione di fritti caldi: supplì al telefono, crocchetta di patate, supplì carbonara o amatriciana',
      den: 'Hot fried selection: classic supplì, potato croquette, carbonara or amatriciana supplì', des: 'Selección de fritos calientes: supplì clásico, croqueta de patata, supplì carbonara o amatriciana' },
    { it: 'Happy hour', en: 'Happy hour', es: 'Happy hour', p: '12',
      dit: 'Tagliere misto di salumi, stuzzichini e pizza al taglio',
      den: 'Mixed cold cuts board, nibbles and pizza by the slice', des: 'Tabla mixta de embutidos, aperitivos y pizza al corte' },
    { it: 'Aperitagliere', en: 'Aperitagliere', es: 'Aperitagliere', p: '15',
      dit: 'Tagliere misto di salumi e formaggi, olive, sottoli, con una focaccia vuota',
      den: 'Mixed cold cuts and cheese board, olives, preserves, with a plain focaccia', des: 'Tabla mixta de embutidos y quesos, aceitunas, encurtidos y una focaccia' } ] } ] },

/* ══ IX ══ COCKTAIL ═══════════════════════════════════════════════════════ */
{ id: 'cocktail', it: 'Cocktail', en: 'Cocktails', es: 'Cócteles', suffissoSezione: '7',
  gruppi: [ { suffisso: '7', voci: [
    { it: 'Aperol Spritz', en: 'Aperol Spritz', es: 'Aperol Spritz', dit: 'Aperol, prosecco, soda, arancia',
      den: 'Aperol, prosecco, soda, orange', des: 'Aperol, prosecco, soda y naranja' },
    { it: 'Campari Spritz', en: 'Campari Spritz', es: 'Campari Spritz', dit: 'Campari, prosecco, soda, arancia',
      den: 'Campari, prosecco, soda, orange', des: 'Campari, prosecco, soda y naranja' },
    { it: 'Hugo Spritz', en: 'Hugo Spritz', es: 'Hugo Spritz',
      dit: 'Prosecco, sciroppo di sambuco, soda, menta, lime',
      den: 'Prosecco, elderflower, soda, mint, lime', des: 'Prosecco, sirope de saúco, soda, menta y lima' },
    { it: 'Limoncello Spritz', en: 'Limoncello Spritz', es: 'Limoncello Spritz',
      dit: 'Limoncello, prosecco, soda, limone', den: 'Limoncello, prosecco, soda, lemon', des: 'Limoncello, prosecco, soda y limón' },
    { it: 'Passion Spritz', en: 'Passion Spritz', es: 'Passion Spritz',
      dit: 'Prosecco, liquore al frutto della passione, soda, frutta fresca',
      den: 'Prosecco, passion fruit liqueur, soda, fresh fruit', des: 'Prosecco, licor de maracuyá, soda y fruta fresca' },
    { it: 'Bellini', en: 'Bellini', es: 'Bellini', dit: 'Prosecco, purea di pesca',
      den: 'Prosecco, peach purée', des: 'Prosecco y puré de melocotón' },
    { it: 'Mojito', en: 'Mojito', es: 'Mojito', dit: 'Rum bianco, zucchero di canna, lime, menta, soda',
      den: 'White rum, cane sugar, lime, mint, soda', des: 'Ron blanco, azúcar de caña, lima, menta y soda' },
    { it: 'Mimosa', en: 'Mimosa', es: 'Mimosa', dit: 'Prosecco, succo d’arancia',
      den: 'Prosecco, orange juice', des: 'Prosecco y zumo de naranja' },
    { it: 'Rum & Cola', en: 'Rum & Cola', es: 'Rum & Cola', dit: 'Rum scuro, cola, lime',
      den: 'Dark rum, cola, lime', des: 'Ron oscuro, cola y lima' },
    { it: 'Caipiroska', en: 'Caipiroska', es: 'Caipiroska', dit: 'Vodka, zucchero di canna, lime',
      den: 'Vodka, cane sugar, lime', des: 'Vodka, azúcar de caña y lima' },
    { it: 'Caipiroska alla fragola', en: 'Strawberry Caipiroska', es: 'Caipiroska de fresa',
      dit: 'Vodka, lime, zucchero di canna, fragole fresche',
      den: 'Vodka, lime, cane sugar, fresh strawberries', des: 'Vodka, lima, azúcar de caña y fresas frescas' },
    { it: 'Negroni', en: 'Negroni', es: 'Negroni', dit: 'Gin, vermouth rosso, Campari',
      den: 'Gin, red vermouth, Campari', des: 'Ginebra, vermut rojo y Campari' },
    { it: 'Negroni Sbagliato', en: 'Negroni Sbagliato', es: 'Negroni Sbagliato',
      dit: 'Prosecco, vermouth rosso, Campari', den: 'Prosecco, red vermouth, Campari', des: 'Prosecco, vermut rojo y Campari' },
    { it: 'Americano', en: 'Americano', es: 'Americano', dit: 'Campari, vermouth rosso, soda',
      den: 'Campari, red vermouth, soda', des: 'Campari, vermut rojo y soda' },
    { it: 'Gin Tonic', en: 'Gin & Tonic', es: 'Gin Tonic', dit: 'Gin, acqua tonica, lime o limone',
      den: 'Gin, tonic water, lime or lemon', des: 'Ginebra, tónica y lima o limón' },
    { it: 'Moscow Mule', en: 'Moscow Mule', es: 'Moscow Mule', dit: 'Vodka, ginger beer, succo di lime',
      den: 'Vodka, ginger beer, lime juice', des: 'Vodka, ginger beer y zumo de lima' },
    { it: 'Bailey Martini', en: 'Bailey Martini', es: 'Bailey Martini', dit: 'Vodka, Baileys', den: 'Vodka, Baileys', des: 'Vodka y Baileys' },
    { it: 'Malibu & Cola', en: 'Malibu & Cola', es: 'Malibu & Cola', dit: 'Malibu, cola, lime',
      den: 'Malibu, cola, lime', des: 'Malibu, cola y lima' } ] } ] },

/* ══ X ═══ BEVANDE ════════════════════════════════════════════════════════ */
{ id: 'bevande', it: 'Bevande', en: 'Drinks', es: 'Bebidas',
  gruppi: [ { fitto: true, voci: [
    { it: 'Acqua 0,5 L', en: 'Water 0.5 L', es: 'Agua 0,5 L', p: '1,50' },
    { it: 'Acqua 0,75 L', en: 'Water 0.75 L', es: 'Agua 0,75 L', p: '3,00' },
    { it: 'Succhi di frutta', en: 'Fruit juice', es: 'Zumos de fruta', p: '3,00' },
    { it: 'Tè alla pesca o limone', en: 'Peach or lemon iced tea', es: 'Té de melocotón o limón', p: '3,00' },
    { it: 'Tè della casa', en: 'House iced tea', es: 'Té de la casa', p: '2,50' },
    { it: 'Spremuta d’arancia', en: 'Fresh orange juice', es: 'Zumo de naranja natural', p: '4,00' },
    { it: 'Spremuta di pompelmo', en: 'Fresh grapefruit juice', es: 'Zumo de pomelo natural', p: '4,00' },
    { it: 'Coca-Cola, Fanta, Sprite', en: 'Coca-Cola, Fanta, Sprite', es: 'Coca-Cola, Fanta, Sprite', p: '3,00' },
    { it: 'Chinotto', en: 'Chinotto', es: 'Chinotto', p: '3,00' },
    { it: 'Schweppes limone', en: 'Schweppes lemon', es: 'Schweppes limón', p: '3,50' },
    { it: 'Schweppes tonica', en: 'Schweppes tonic', es: 'Schweppes tónica', p: '3,50' },
    { it: 'Red Bull', en: 'Red Bull', es: 'Red Bull', p: '3,50',
      dit: 'Energy drink, Zero, Pink Edition', den: 'Energy drink, Zero, Pink Edition', des: 'Energy drink, Zero, Pink Edition' },
    { it: 'Crodino', en: 'Crodino', es: 'Crodino', p: '3,50' },
    { it: 'Campari Soda', en: 'Campari Soda', es: 'Campari Soda', p: '3,50' },
    { it: 'Campari Soda corretto', en: 'Campari Soda with a shot', es: 'Campari Soda con licor', p: '3,90' },
    { it: 'Corona', en: 'Corona', es: 'Corona', p: '4,00' },
    { it: 'Corona 0', en: 'Corona 0', es: 'Corona 0', p: '4,00' },
    { it: 'Messina 33 cl', en: 'Messina 33 cl', es: 'Messina 33 cl', p: '4,00' },
    { it: 'Ichnusa non filtrata', en: 'Ichnusa unfiltered', es: 'Ichnusa sin filtrar', p: '4,00' },
    { it: 'Birra alla spina', en: 'Draught beer', es: 'Cerveza de barril', p: '6,00',
      dit: 'Heineken o Moretti', den: 'Heineken or Moretti', des: 'Heineken o Moretti' },
    { it: 'Calice di Prosecco', en: 'Glass of Prosecco', es: 'Copa de Prosecco', p: '6,00' },
    { it: 'Calice di vino bianco', en: 'Glass of white wine', es: 'Copa de vino blanco', p: '6,00' },
    { it: 'Calice di vino rosso', en: 'Glass of red wine', es: 'Copa de vino tinto', p: '6,00' },
    { it: 'Amari', en: 'Amaro', es: 'Amaro', p: '4,00' },
    { it: 'Whisky', en: 'Whisky', es: 'Whisky', p: '4,00' } ] } ] },

/* ══ XI ══ AL TAGLIO (108) ════════════════════════════════════════════════ */
{ id: 'taglio', it: 'Pizza al taglio', en: 'Pizza by the slice', es: 'Pizza al corte',
  ore: { it: 'TUTTO IL GIORNO · MERULANA 108', en: 'ALL DAY · MERULANA 108', es: 'TODO EL DÍA · MERULANA 108' },
  foto: '../img/w_foto_tranci.jpg',
  nota: { it: 'Due porte più in là, al 108. Prezzo al trancio. Pizze tonde da asporto su ordinazione.',
          en: 'Two doors down, at number 108. Price per slice. Round pizzas to take away, on order.', es: 'Dos puertas más allá, en el 108. Precio por porción. Pizzas redondas para llevar por encargo.' },
  gruppi: [ { voci: [
    { it: 'Bianca', en: 'White', es: 'Blanca', p: '2,50' },
    { it: 'Rossa, Marinara, Patate', en: 'Tomato, Marinara, Potato', es: 'Roja, Marinara, Patata', p: '4,00' },
    { it: 'Margherita', en: 'Margherita', es: 'Margherita', p: '4,50' },
    { it: 'Crostini', en: 'Crostini', es: 'Crostini', p: '5,00' },
    { it: 'Speciali', en: 'Speciality', es: 'Especiales', p: '6,00' },
    { it: 'Ripiene', en: 'Filled', es: 'Rellenas', p: '6,00' },
    { it: 'Calzoni', en: 'Calzoni', es: 'Calzoni', p: '5,00' },
    { it: 'Bibita in lattina', en: 'Canned drink', es: 'Refresco en lata', p: '3,50' } ] } ] }

];
